<?php /*
    Copyright (C) Nathanael Schaeffer

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/ ?>
<div style="margin: 5px; float: left bottom;"><a href="http://natnco.free.fr">
	<img src="gfx/Natnco_LogoV1_xs.png" style="border: 0px solid ; width: 200px; height: 97px;" align="left"></a>
	<div style="margin: 0px 0px 0px -120px; float: right;"><img src="gfx/ski_small.png"></div>

<div style="text-align: center;"><small><br>
<i>Sites index&eacute;s :</i> <a href="http://www.bivouak.net/">bivouak.net</a>, 
	<!-- <a href="http://blms.free.fr/">BLMS</a>, -->
	<!-- <a href="http://www.clubalpin-grenoble.com/crrandoski.php">CAF de l'Isère</a>, -->
	<a href="http://www.camptocamp.org/">camptocamp.org (c2c)</a>,
	<a href="http://www.gulliver.it/">gulliver.it</a>, 
	<!-- <a href="http://www.ohm-chamonix.com/">ohm-chamonix.com</a>, -->
	<!-- <a href="http://www.montagneinfo.net/">montagneinfo.net (SNGM)</a>, -->
	<!-- <a href="http://nimp.crew.free.fr/">Nimp'Crew</a>, -->
	<a href="http://www.skitour.fr/">Skitour</a>,
	<a href="http://www.volopress.net/">Volopress</a>.
<br>
<i>D'autres sites devraient &ecirc;tre index&eacute;s ? Remarques ? suggestions ? faites-le savoir</i> : <img src="gfx/c2c_cour.png">

</small>
</div>
</div>
<script type="text/javascript">
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');
ga('create','UA-2814179-4');ga('send','pageview',{'anonymizeIp': true});
</script>
