#!/bin/bash
#    fetch metaskirando data
#    Copyright (C) Nathanael Schaeffer
#    Copyright (C) Camptocamp Association
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

curl='curl --max-time 300 --silent'
ua='metaskirando bot'
odir="/var/www/metaskirando.camptocamp.org/private/data"
t=180

mfadr="http://france.meteofrance.com/js/dwr/call/plaincall/montagneComponent.rechercheStationImagesNivoses.dwr?callCount=1&scriptSessionId=montagneComponent&c0-scriptName=montagneComponent&c0-methodName=rechercheStationImagesNivoses&c0-id=0&batchId=0&c0-param0=string%3A"

download () {
  TMP=$(mktemp)
  sleep $((RANDOM % $t))

  if test -z "$3"; then
    $curl -H "User-Agent: $ua" $2 > $TMP && mv $TMP $odir/"$1".web
  else
    $curl -H "User-Agent: $ua" -H "Host: $3" $2 > $TMP && mv $TMP $odir/"$1".web
  fi

  if [ $? == 0 ]; then
    echo "fetched $2"
  else
    echo "failed fetching $2"
  fi
}

download skitour      "http://www.skitour.fr/topos/dernieres-sorties.php?nbr=100" &
download volo         "http://www.volopress.net/volo/spip.php?rubrique2" &
download c2c          "http://localhost/outings/list/act/1/layout/light/npp/60" www.camptocamp.org &
download SNGM         "http://www.montagneinfo.net/flux/activites.php?NoIDActivite=11" &
download gulliver.sr  "http://www.gulliver.it/sci-ripido/" &
download gulliver.sa  "http://www.gulliver.it/scialpinismo/" &
download bivouak      "http://www.bivouak.net/accueil/index.php?id_sport=1" &

($curl "${mfadr}ALPES-NORD"   && \
 $curl "${mfadr}ALPES-SUD"    && \
 $curl "${mfadr}PYRENEES-EST" && \
 $curl "${mfadr}PYRENEES-OUEST") > $odir/mf.web

if [ $? == 0 ]; then
  echo "extracting links from MF pages."
  egrep 'Porte|Bauges|Mercantour|Parpaillon|Puigmal|Hospitalet|Aiguillettes' $odir/mf.web > $odir/nivo_links.web
else
  echo "failed fetching at least one MF page."
fi

