<?php /*
    Copyright (C) Nathanael Schaeffer

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/ ?>
<p class="menu"><span class="menu">
<a href="index.php" title="Rechercher les dernières sorties de ski de rando !">Accueil</a> ||
<a href="Nivo.php" title="Nivoses et Météo">Nivo & Météo</a> ||
<a href="http://www.skitour.fr/webcams/" title="Webcams de stations de skis (skitour.fr)">Webcams Montagne</a> ||
<a href="diffusion.php" title="Diffuser l'info sur votre site !">Diffusion</a> ||
<!-- <a href="archeovolo.php" title="Rechercher une course chez Volopress (depuis 2001)">ArchéoVologie</a> || -->
<a href="prefs.php" title="D&eacute;finir mes pr&eacute;f&eacute;rences et mes régions">Pr&eacute;f&eacute;rences</a>
</span>
</p>

<div style="position: absolute; top: 0px; right: 0px;"><img src="gfx/surf_small2.png"></div>
<div style="padding: 40px 50px; float: right;">&nbsp;</div>
